//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfClientProject.ServiceReferenceBank {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfClientProject.ServiceReferenceBank.BankAccount))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfClientProject.ServiceReferenceBank.MyAction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfClientProject.ServiceReferenceBank.AccountAction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfClientProject.ServiceReferenceBank.User))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankAccount", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class BankAccount : WpfClientProject.ServiceReferenceBank.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool adultAcouuntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int bankAcuuntNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool canTradeStocksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool canTransferOverSeasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool canloanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfClientProject.ServiceReferenceBank.Customers customerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool personalAcouuntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int secretCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool adultAcouunt {
            get {
                return this.adultAcouuntField;
            }
            set {
                if ((this.adultAcouuntField.Equals(value) != true)) {
                    this.adultAcouuntField = value;
                    this.RaisePropertyChanged("adultAcouunt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int bankAcuuntNum {
            get {
                return this.bankAcuuntNumField;
            }
            set {
                if ((this.bankAcuuntNumField.Equals(value) != true)) {
                    this.bankAcuuntNumField = value;
                    this.RaisePropertyChanged("bankAcuuntNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool canTradeStocks {
            get {
                return this.canTradeStocksField;
            }
            set {
                if ((this.canTradeStocksField.Equals(value) != true)) {
                    this.canTradeStocksField = value;
                    this.RaisePropertyChanged("canTradeStocks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool canTransferOverSeas {
            get {
                return this.canTransferOverSeasField;
            }
            set {
                if ((this.canTransferOverSeasField.Equals(value) != true)) {
                    this.canTransferOverSeasField = value;
                    this.RaisePropertyChanged("canTransferOverSeas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool canloan {
            get {
                return this.canloanField;
            }
            set {
                if ((this.canloanField.Equals(value) != true)) {
                    this.canloanField = value;
                    this.RaisePropertyChanged("canloan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfClientProject.ServiceReferenceBank.Customers customer {
            get {
                return this.customerField;
            }
            set {
                if ((object.ReferenceEquals(this.customerField, value) != true)) {
                    this.customerField = value;
                    this.RaisePropertyChanged("customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool personalAcouunt {
            get {
                return this.personalAcouuntField;
            }
            set {
                if ((this.personalAcouuntField.Equals(value) != true)) {
                    this.personalAcouuntField = value;
                    this.RaisePropertyChanged("personalAcouunt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int secretCode {
            get {
                return this.secretCodeField;
            }
            set {
                if ((this.secretCodeField.Equals(value) != true)) {
                    this.secretCodeField = value;
                    this.RaisePropertyChanged("secretCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyAction", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class MyAction : WpfClientProject.ServiceReferenceBank.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string actionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double commissionTakenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int minRankField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string actionName {
            get {
                return this.actionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.actionNameField, value) != true)) {
                    this.actionNameField = value;
                    this.RaisePropertyChanged("actionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double commissionTaken {
            get {
                return this.commissionTakenField;
            }
            set {
                if ((this.commissionTakenField.Equals(value) != true)) {
                    this.commissionTakenField = value;
                    this.RaisePropertyChanged("commissionTaken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int minRank {
            get {
                return this.minRankField;
            }
            set {
                if ((this.minRankField.Equals(value) != true)) {
                    this.minRankField = value;
                    this.RaisePropertyChanged("minRank");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountAction", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class AccountAction : WpfClientProject.ServiceReferenceBank.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfClientProject.ServiceReferenceBank.MyAction ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfClientProject.ServiceReferenceBank.BankAccount BankAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimaStampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfClientProject.ServiceReferenceBank.MyAction Action {
            get {
                return this.ActionField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionField, value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfClientProject.ServiceReferenceBank.BankAccount BankAccount {
            get {
                return this.BankAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.BankAccountField, value) != true)) {
                    this.BankAccountField = value;
                    this.RaisePropertyChanged("BankAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimaStamp {
            get {
                return this.TimaStampField;
            }
            set {
                if ((this.TimaStampField.Equals(value) != true)) {
                    this.TimaStampField = value;
                    this.RaisePropertyChanged("TimaStamp");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfClientProject.ServiceReferenceBank.Customers))]
    public partial class User : WpfClientProject.ServiceReferenceBank.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsWorkerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhonenumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WorkerRankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string realidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                if ((this.BirthdayField.Equals(value) != true)) {
                    this.BirthdayField = value;
                    this.RaisePropertyChanged("Birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsWorker {
            get {
                return this.IsWorkerField;
            }
            set {
                if ((this.IsWorkerField.Equals(value) != true)) {
                    this.IsWorkerField = value;
                    this.RaisePropertyChanged("IsWorker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phonenum {
            get {
                return this.PhonenumField;
            }
            set {
                if ((object.ReferenceEquals(this.PhonenumField, value) != true)) {
                    this.PhonenumField = value;
                    this.RaisePropertyChanged("Phonenum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WorkerRank {
            get {
                return this.WorkerRankField;
            }
            set {
                if ((this.WorkerRankField.Equals(value) != true)) {
                    this.WorkerRankField = value;
                    this.RaisePropertyChanged("WorkerRank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string realid {
            get {
                return this.realidField;
            }
            set {
                if ((object.ReferenceEquals(this.realidField, value) != true)) {
                    this.realidField = value;
                    this.RaisePropertyChanged("realid");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customers", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Customers : WpfClientProject.ServiceReferenceBank.User {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfClientProject.ServiceReferenceBank.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateOfJoiningField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isNativeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfClientProject.ServiceReferenceBank.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateOfJoining {
            get {
                return this.dateOfJoiningField;
            }
            set {
                if ((this.dateOfJoiningField.Equals(value) != true)) {
                    this.dateOfJoiningField = value;
                    this.RaisePropertyChanged("dateOfJoining");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isNative {
            get {
                return this.isNativeField;
            }
            set {
                if ((this.isNativeField.Equals(value) != true)) {
                    this.isNativeField = value;
                    this.RaisePropertyChanged("isNative");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="UserList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="User")]
    [System.SerializableAttribute()]
    public class UserList : System.Collections.Generic.List<WpfClientProject.ServiceReferenceBank.User> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="BankAccountList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="BankAccount")]
    [System.SerializableAttribute()]
    public class BankAccountList : System.Collections.Generic.List<WpfClientProject.ServiceReferenceBank.BankAccount> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="CustomersList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Customers")]
    [System.SerializableAttribute()]
    public class CustomersList : System.Collections.Generic.List<WpfClientProject.ServiceReferenceBank.Customers> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ActionList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="MyAction")]
    [System.SerializableAttribute()]
    public class ActionList : System.Collections.Generic.List<WpfClientProject.ServiceReferenceBank.MyAction> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AccountActionList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="AccountAction")]
    [System.SerializableAttribute()]
    public class AccountActionList : System.Collections.Generic.List<WpfClientProject.ServiceReferenceBank.AccountAction> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceBank.IServiceBase")]
    public interface IServiceBase {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/InsertUser", ReplyAction="http://tempuri.org/IServiceBase/InsertUserResponse")]
        int InsertUser(WpfClientProject.ServiceReferenceBank.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/InsertUser", ReplyAction="http://tempuri.org/IServiceBase/InsertUserResponse")]
        System.Threading.Tasks.Task<int> InsertUserAsync(WpfClientProject.ServiceReferenceBank.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/UpdateUser", ReplyAction="http://tempuri.org/IServiceBase/UpdateUserResponse")]
        int UpdateUser(WpfClientProject.ServiceReferenceBank.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/UpdateUser", ReplyAction="http://tempuri.org/IServiceBase/UpdateUserResponse")]
        System.Threading.Tasks.Task<int> UpdateUserAsync(WpfClientProject.ServiceReferenceBank.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/DeleteUser", ReplyAction="http://tempuri.org/IServiceBase/DeleteUserResponse")]
        int DeleteUser(WpfClientProject.ServiceReferenceBank.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/DeleteUser", ReplyAction="http://tempuri.org/IServiceBase/DeleteUserResponse")]
        System.Threading.Tasks.Task<int> DeleteUserAsync(WpfClientProject.ServiceReferenceBank.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/GetAllUsers", ReplyAction="http://tempuri.org/IServiceBase/GetAllUsersResponse")]
        WpfClientProject.ServiceReferenceBank.UserList GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/GetAllUsers", ReplyAction="http://tempuri.org/IServiceBase/GetAllUsersResponse")]
        System.Threading.Tasks.Task<WpfClientProject.ServiceReferenceBank.UserList> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/GetAllBankAccountList", ReplyAction="http://tempuri.org/IServiceBase/GetAllBankAccountListResponse")]
        WpfClientProject.ServiceReferenceBank.BankAccountList GetAllBankAccountList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/GetAllBankAccountList", ReplyAction="http://tempuri.org/IServiceBase/GetAllBankAccountListResponse")]
        System.Threading.Tasks.Task<WpfClientProject.ServiceReferenceBank.BankAccountList> GetAllBankAccountListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/InsertIntoBankAcouunt", ReplyAction="http://tempuri.org/IServiceBase/InsertIntoBankAcouuntResponse")]
        int InsertIntoBankAcouunt(WpfClientProject.ServiceReferenceBank.BankAccount bankAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/InsertIntoBankAcouunt", ReplyAction="http://tempuri.org/IServiceBase/InsertIntoBankAcouuntResponse")]
        System.Threading.Tasks.Task<int> InsertIntoBankAcouuntAsync(WpfClientProject.ServiceReferenceBank.BankAccount bankAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/UpdateBankAcouunt", ReplyAction="http://tempuri.org/IServiceBase/UpdateBankAcouuntResponse")]
        int UpdateBankAcouunt(WpfClientProject.ServiceReferenceBank.BankAccount bankAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/UpdateBankAcouunt", ReplyAction="http://tempuri.org/IServiceBase/UpdateBankAcouuntResponse")]
        System.Threading.Tasks.Task<int> UpdateBankAcouuntAsync(WpfClientProject.ServiceReferenceBank.BankAccount bankAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/DeleteBankAcouunt", ReplyAction="http://tempuri.org/IServiceBase/DeleteBankAcouuntResponse")]
        int DeleteBankAcouunt(WpfClientProject.ServiceReferenceBank.BankAccount bankAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/DeleteBankAcouunt", ReplyAction="http://tempuri.org/IServiceBase/DeleteBankAcouuntResponse")]
        System.Threading.Tasks.Task<int> DeleteBankAcouuntAsync(WpfClientProject.ServiceReferenceBank.BankAccount bankAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/InsertIntoCustomers", ReplyAction="http://tempuri.org/IServiceBase/InsertIntoCustomersResponse")]
        int InsertIntoCustomers(WpfClientProject.ServiceReferenceBank.Customers customers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/InsertIntoCustomers", ReplyAction="http://tempuri.org/IServiceBase/InsertIntoCustomersResponse")]
        System.Threading.Tasks.Task<int> InsertIntoCustomersAsync(WpfClientProject.ServiceReferenceBank.Customers customers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/UpgdateCustomers", ReplyAction="http://tempuri.org/IServiceBase/UpgdateCustomersResponse")]
        int UpgdateCustomers(WpfClientProject.ServiceReferenceBank.Customers customers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/UpgdateCustomers", ReplyAction="http://tempuri.org/IServiceBase/UpgdateCustomersResponse")]
        System.Threading.Tasks.Task<int> UpgdateCustomersAsync(WpfClientProject.ServiceReferenceBank.Customers customers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/DeleteCustomers", ReplyAction="http://tempuri.org/IServiceBase/DeleteCustomersResponse")]
        int DeleteCustomers(WpfClientProject.ServiceReferenceBank.Customers customers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/DeleteCustomers", ReplyAction="http://tempuri.org/IServiceBase/DeleteCustomersResponse")]
        System.Threading.Tasks.Task<int> DeleteCustomersAsync(WpfClientProject.ServiceReferenceBank.Customers customers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/GetAllCustomers", ReplyAction="http://tempuri.org/IServiceBase/GetAllCustomersResponse")]
        WpfClientProject.ServiceReferenceBank.CustomersList GetAllCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/GetAllCustomers", ReplyAction="http://tempuri.org/IServiceBase/GetAllCustomersResponse")]
        System.Threading.Tasks.Task<WpfClientProject.ServiceReferenceBank.CustomersList> GetAllCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/InsertIntoAction", ReplyAction="http://tempuri.org/IServiceBase/InsertIntoActionResponse")]
        int InsertIntoAction(WpfClientProject.ServiceReferenceBank.MyAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/InsertIntoAction", ReplyAction="http://tempuri.org/IServiceBase/InsertIntoActionResponse")]
        System.Threading.Tasks.Task<int> InsertIntoActionAsync(WpfClientProject.ServiceReferenceBank.MyAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/UpdateAction", ReplyAction="http://tempuri.org/IServiceBase/UpdateActionResponse")]
        int UpdateAction(WpfClientProject.ServiceReferenceBank.MyAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/UpdateAction", ReplyAction="http://tempuri.org/IServiceBase/UpdateActionResponse")]
        System.Threading.Tasks.Task<int> UpdateActionAsync(WpfClientProject.ServiceReferenceBank.MyAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/DeleteAction", ReplyAction="http://tempuri.org/IServiceBase/DeleteActionResponse")]
        int DeleteAction(WpfClientProject.ServiceReferenceBank.MyAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/DeleteAction", ReplyAction="http://tempuri.org/IServiceBase/DeleteActionResponse")]
        System.Threading.Tasks.Task<int> DeleteActionAsync(WpfClientProject.ServiceReferenceBank.MyAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/GetAllActions", ReplyAction="http://tempuri.org/IServiceBase/GetAllActionsResponse")]
        WpfClientProject.ServiceReferenceBank.ActionList GetAllActions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/GetAllActions", ReplyAction="http://tempuri.org/IServiceBase/GetAllActionsResponse")]
        System.Threading.Tasks.Task<WpfClientProject.ServiceReferenceBank.ActionList> GetAllActionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/UserLogin", ReplyAction="http://tempuri.org/IServiceBase/UserLoginResponse")]
        WpfClientProject.ServiceReferenceBank.User UserLogin(WpfClientProject.ServiceReferenceBank.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/UserLogin", ReplyAction="http://tempuri.org/IServiceBase/UserLoginResponse")]
        System.Threading.Tasks.Task<WpfClientProject.ServiceReferenceBank.User> UserLoginAsync(WpfClientProject.ServiceReferenceBank.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/Insertintoacountaction", ReplyAction="http://tempuri.org/IServiceBase/InsertintoacountactionResponse")]
        int Insertintoacountaction(WpfClientProject.ServiceReferenceBank.AccountAction account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/Insertintoacountaction", ReplyAction="http://tempuri.org/IServiceBase/InsertintoacountactionResponse")]
        System.Threading.Tasks.Task<int> InsertintoacountactionAsync(WpfClientProject.ServiceReferenceBank.AccountAction account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/UpdateIntoAcountAction", ReplyAction="http://tempuri.org/IServiceBase/UpdateIntoAcountActionResponse")]
        int UpdateIntoAcountAction(WpfClientProject.ServiceReferenceBank.AccountAction account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/UpdateIntoAcountAction", ReplyAction="http://tempuri.org/IServiceBase/UpdateIntoAcountActionResponse")]
        System.Threading.Tasks.Task<int> UpdateIntoAcountActionAsync(WpfClientProject.ServiceReferenceBank.AccountAction account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/DeleteIntoAcountAction", ReplyAction="http://tempuri.org/IServiceBase/DeleteIntoAcountActionResponse")]
        int DeleteIntoAcountAction(WpfClientProject.ServiceReferenceBank.AccountAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/DeleteIntoAcountAction", ReplyAction="http://tempuri.org/IServiceBase/DeleteIntoAcountActionResponse")]
        System.Threading.Tasks.Task<int> DeleteIntoAcountActionAsync(WpfClientProject.ServiceReferenceBank.AccountAction action);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/SelectAllAccountAction", ReplyAction="http://tempuri.org/IServiceBase/SelectAllAccountActionResponse")]
        WpfClientProject.ServiceReferenceBank.AccountActionList SelectAllAccountAction();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBase/SelectAllAccountAction", ReplyAction="http://tempuri.org/IServiceBase/SelectAllAccountActionResponse")]
        System.Threading.Tasks.Task<WpfClientProject.ServiceReferenceBank.AccountActionList> SelectAllAccountActionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceBaseChannel : WpfClientProject.ServiceReferenceBank.IServiceBase, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceBaseClient : System.ServiceModel.ClientBase<WpfClientProject.ServiceReferenceBank.IServiceBase>, WpfClientProject.ServiceReferenceBank.IServiceBase {
        
        public ServiceBaseClient() {
        }
        
        public ServiceBaseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceBaseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBaseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBaseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InsertUser(WpfClientProject.ServiceReferenceBank.User user) {
            return base.Channel.InsertUser(user);
        }
        
        public System.Threading.Tasks.Task<int> InsertUserAsync(WpfClientProject.ServiceReferenceBank.User user) {
            return base.Channel.InsertUserAsync(user);
        }
        
        public int UpdateUser(WpfClientProject.ServiceReferenceBank.User user) {
            return base.Channel.UpdateUser(user);
        }
        
        public System.Threading.Tasks.Task<int> UpdateUserAsync(WpfClientProject.ServiceReferenceBank.User user) {
            return base.Channel.UpdateUserAsync(user);
        }
        
        public int DeleteUser(WpfClientProject.ServiceReferenceBank.User user) {
            return base.Channel.DeleteUser(user);
        }
        
        public System.Threading.Tasks.Task<int> DeleteUserAsync(WpfClientProject.ServiceReferenceBank.User user) {
            return base.Channel.DeleteUserAsync(user);
        }
        
        public WpfClientProject.ServiceReferenceBank.UserList GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<WpfClientProject.ServiceReferenceBank.UserList> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public WpfClientProject.ServiceReferenceBank.BankAccountList GetAllBankAccountList() {
            return base.Channel.GetAllBankAccountList();
        }
        
        public System.Threading.Tasks.Task<WpfClientProject.ServiceReferenceBank.BankAccountList> GetAllBankAccountListAsync() {
            return base.Channel.GetAllBankAccountListAsync();
        }
        
        public int InsertIntoBankAcouunt(WpfClientProject.ServiceReferenceBank.BankAccount bankAccount) {
            return base.Channel.InsertIntoBankAcouunt(bankAccount);
        }
        
        public System.Threading.Tasks.Task<int> InsertIntoBankAcouuntAsync(WpfClientProject.ServiceReferenceBank.BankAccount bankAccount) {
            return base.Channel.InsertIntoBankAcouuntAsync(bankAccount);
        }
        
        public int UpdateBankAcouunt(WpfClientProject.ServiceReferenceBank.BankAccount bankAccount) {
            return base.Channel.UpdateBankAcouunt(bankAccount);
        }
        
        public System.Threading.Tasks.Task<int> UpdateBankAcouuntAsync(WpfClientProject.ServiceReferenceBank.BankAccount bankAccount) {
            return base.Channel.UpdateBankAcouuntAsync(bankAccount);
        }
        
        public int DeleteBankAcouunt(WpfClientProject.ServiceReferenceBank.BankAccount bankAccount) {
            return base.Channel.DeleteBankAcouunt(bankAccount);
        }
        
        public System.Threading.Tasks.Task<int> DeleteBankAcouuntAsync(WpfClientProject.ServiceReferenceBank.BankAccount bankAccount) {
            return base.Channel.DeleteBankAcouuntAsync(bankAccount);
        }
        
        public int InsertIntoCustomers(WpfClientProject.ServiceReferenceBank.Customers customers) {
            return base.Channel.InsertIntoCustomers(customers);
        }
        
        public System.Threading.Tasks.Task<int> InsertIntoCustomersAsync(WpfClientProject.ServiceReferenceBank.Customers customers) {
            return base.Channel.InsertIntoCustomersAsync(customers);
        }
        
        public int UpgdateCustomers(WpfClientProject.ServiceReferenceBank.Customers customers) {
            return base.Channel.UpgdateCustomers(customers);
        }
        
        public System.Threading.Tasks.Task<int> UpgdateCustomersAsync(WpfClientProject.ServiceReferenceBank.Customers customers) {
            return base.Channel.UpgdateCustomersAsync(customers);
        }
        
        public int DeleteCustomers(WpfClientProject.ServiceReferenceBank.Customers customers) {
            return base.Channel.DeleteCustomers(customers);
        }
        
        public System.Threading.Tasks.Task<int> DeleteCustomersAsync(WpfClientProject.ServiceReferenceBank.Customers customers) {
            return base.Channel.DeleteCustomersAsync(customers);
        }
        
        public WpfClientProject.ServiceReferenceBank.CustomersList GetAllCustomers() {
            return base.Channel.GetAllCustomers();
        }
        
        public System.Threading.Tasks.Task<WpfClientProject.ServiceReferenceBank.CustomersList> GetAllCustomersAsync() {
            return base.Channel.GetAllCustomersAsync();
        }
        
        public int InsertIntoAction(WpfClientProject.ServiceReferenceBank.MyAction action) {
            return base.Channel.InsertIntoAction(action);
        }
        
        public System.Threading.Tasks.Task<int> InsertIntoActionAsync(WpfClientProject.ServiceReferenceBank.MyAction action) {
            return base.Channel.InsertIntoActionAsync(action);
        }
        
        public int UpdateAction(WpfClientProject.ServiceReferenceBank.MyAction action) {
            return base.Channel.UpdateAction(action);
        }
        
        public System.Threading.Tasks.Task<int> UpdateActionAsync(WpfClientProject.ServiceReferenceBank.MyAction action) {
            return base.Channel.UpdateActionAsync(action);
        }
        
        public int DeleteAction(WpfClientProject.ServiceReferenceBank.MyAction action) {
            return base.Channel.DeleteAction(action);
        }
        
        public System.Threading.Tasks.Task<int> DeleteActionAsync(WpfClientProject.ServiceReferenceBank.MyAction action) {
            return base.Channel.DeleteActionAsync(action);
        }
        
        public WpfClientProject.ServiceReferenceBank.ActionList GetAllActions() {
            return base.Channel.GetAllActions();
        }
        
        public System.Threading.Tasks.Task<WpfClientProject.ServiceReferenceBank.ActionList> GetAllActionsAsync() {
            return base.Channel.GetAllActionsAsync();
        }
        
        public WpfClientProject.ServiceReferenceBank.User UserLogin(WpfClientProject.ServiceReferenceBank.User user) {
            return base.Channel.UserLogin(user);
        }
        
        public System.Threading.Tasks.Task<WpfClientProject.ServiceReferenceBank.User> UserLoginAsync(WpfClientProject.ServiceReferenceBank.User user) {
            return base.Channel.UserLoginAsync(user);
        }
        
        public int Insertintoacountaction(WpfClientProject.ServiceReferenceBank.AccountAction account) {
            return base.Channel.Insertintoacountaction(account);
        }
        
        public System.Threading.Tasks.Task<int> InsertintoacountactionAsync(WpfClientProject.ServiceReferenceBank.AccountAction account) {
            return base.Channel.InsertintoacountactionAsync(account);
        }
        
        public int UpdateIntoAcountAction(WpfClientProject.ServiceReferenceBank.AccountAction account) {
            return base.Channel.UpdateIntoAcountAction(account);
        }
        
        public System.Threading.Tasks.Task<int> UpdateIntoAcountActionAsync(WpfClientProject.ServiceReferenceBank.AccountAction account) {
            return base.Channel.UpdateIntoAcountActionAsync(account);
        }
        
        public int DeleteIntoAcountAction(WpfClientProject.ServiceReferenceBank.AccountAction action) {
            return base.Channel.DeleteIntoAcountAction(action);
        }
        
        public System.Threading.Tasks.Task<int> DeleteIntoAcountActionAsync(WpfClientProject.ServiceReferenceBank.AccountAction action) {
            return base.Channel.DeleteIntoAcountActionAsync(action);
        }
        
        public WpfClientProject.ServiceReferenceBank.AccountActionList SelectAllAccountAction() {
            return base.Channel.SelectAllAccountAction();
        }
        
        public System.Threading.Tasks.Task<WpfClientProject.ServiceReferenceBank.AccountActionList> SelectAllAccountActionAsync() {
            return base.Channel.SelectAllAccountActionAsync();
        }
    }
}
